# Generated by Django 2.2.12 on 2020-05-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='new_field',
        ),
    ]
